### ISSUE TITLE
How does one combine graphql-middleware with nexus-prisma?

### ISSUE THREAD

**Issue by heymartinadams** [prisma-labs/graphql-middleware#245]
The [instructions](https://github.com/prisma-labs/graphql-middleware#how-does-it-work) for `graphql-middleware` are pretty straightforward — but they only seem to apply to [schema-first development](https://www.prisma.io/blog/the-problems-of-schema-first-graphql-development-x1mn4cb0tyl3/) if I’m not mistaken.

I’ve now implemented [nexus-prisma](https://github.com/prisma-labs/nexus-prisma), but since this approach is code-first, the resolvers, when called, haven’t yet compiled into the actual resolvers (if that makes sense?), so I’m receiving the following error message:

```
.../node_modules/graphql-yoga/node_modules/graphql-middleware/dist/validation.js:1
Error: Field Query.name exists in middleware but is missing in Schema.
    at .../node_modules/graphql-yoga/node_modules/graphql-middleware/dist/validation.js:17:27
    at Array.forEach (<anonymous>)
    at .../node_modules/graphql-yoga/node_modules/graphql-middleware/dist/validation.js:15:43
    at Array.forEach (<anonymous>)
    at Object.validateMiddleware (.../node_modules/graphql-yoga/node_modules/graphql-middleware/dist/validation.js:9:29)
    at addMiddlewareToSchema (.../node_modules/graphql-yoga/node_modules/graphql-middleware/dist/middleware.js:19:42)
    at normalisedMiddlewares.reduceRight.schema.schema (.../node_modules/graphql-yoga/node_modules/graphql-middleware/dist/middleware.js:52:87)
    at Array.reduceRight (<anonymous>)
    at applyMiddlewareWithOptions (.../node_modules/graphql-yoga/node_modules/graphql-middleware/dist/middleware.js:51:79)
    at applyMiddleware (.../node_modules/graphql-yoga/node_modules/graphql-middleware/dist/middleware.js:78:12)
```

### index.js

```js
// Packages
import { GraphQLServer } from 'graphql-yoga'
import { nexusPrismaPlugin } from 'nexus-prisma'
import { makeSchema } from 'nexus'

// Types
import types from './types'

// Middleware
import systemLogCreate from './resolvers/mutations/systemLogCreate'
import systemLogErrorCreate from './resolvers/mutations/systemLogErrorCreate'

new GraphQLServer({
  schema: makeSchema({
    types: { ...types, ...resolvers },
    plugins: [nexusPrismaPlugin()]
  }),
  middlewares: [
    systemLogCreate,
    systemLogErrorCreate
]
```

### mutations.js
```js
// Packages
import { mutationType } from 'nexus'
// Components
import systemLogCreate from './System/SystemLog/systemLogCreate'
import systemLogErrorCreate from './System/SystemLog/systemLogErrorCreate'

export default {
  Mutation: mutationType({
    definition(t) {
      t.field('systemLogCreate', {
        type: 'SystemLog',
        resolve: systemLogCreate
      })
      t.field('systemLogErrorCreate', {
        type: 'SystemLogError',
        resolve: systemLogErrorCreate
      })
    }
  })
}
```

### systemLogErrorCreate.js
```js
export default async (resolve, root, args, ctx, info) => {
  // First resolve all resolvers...
  try {
    return await resolve(root, args, ctx, info)
  } catch (err) {
    // ...and if an error occurs in any of them, log it and tie it to session.
    const sessionId = args.sessionId
    delete args.sessionId
    const error = ctx.photon.systemLogErrors.create({
      data: {
        args,
        error: err
      }
    })
    // Throw it to communicate it to browser.
    throw new Error(err)
  }
}
```

**Comment by heymartinadams** [comment]
Sorry, discovered an error in my `nexus` configuration!

### mutations.js

Rather than this:

```js
// Packages
import { mutationType } from 'nexus'
// Components
import systemLogCreate from './System/SystemLog/systemLogCreate'
import systemLogErrorCreate from './System/SystemLog/systemLogErrorCreate'

export default {
  Mutation: mutationType({
    definition(t) {
      t.field('systemLogCreate', systemLogCreate)
      t.field('systemLogErrorCreate', systemLogErrorCreate)
    }
  })
}
```

It needed to be that:

```js
// Packages
import { mutationType } from 'nexus'
// Components
import systemLogCreate from './System/SystemLog/systemLogCreate'
import systemLogErrorCreate from './System/SystemLog/systemLogErrorCreate'

export default {
  Mutation: mutationType({
    definition(t) {
      t.field('systemLogCreate', {
        type: 'SystemLog',
        resolve: systemLogCreate
      })
      t.field('systemLogErrorCreate', {
        type: 'SystemLogError',
        resolve: systemLogErrorCreate
      })
    }
  })
}
```

**Comment by thierryskoda** [comment]
@heymartinadams I'm on the same problem. I'm using Nexus and tried to add a middleware exactly like you did. For me everything works great except that I can't get the error to the browser. Without the middleware, in my browser i'm receiving:

```
data: null
errors: [...]
```

But with the middleware when there's an error in my browser I only receive 

```
data: null
```

Did you have the same problem? 

Thank you!!

**Comment by heymartinadams** [comment]
Just seeing this, @thierryskoda. Decided to not create a GraphQL server, but instead use REST endpoints using Prisma’s new framework.
