### ISSUE TITLE
Support for multiple middlewares

### ISSUE THREAD

**Issue by Faisal-Manzer** [prisma-labs/graphql-middleware#256]
When tried to use multiple middle-wares with a query it failed with the errors below.
```
/Users/user/Desktop/example/node_modules/graphql-middleware/dist/validation.js:20
                    throw new MiddlewareError(`Expected ${type}.${field} to be a function but found ` +
                    ^

MiddlewareError: Expected Query.secured to be a function but found object
    at /Users/user/Desktop/example/node_modules/graphql-middleware/dist/validation.js:20:27
    at Array.forEach (<anonymous>)
    at /Users/user/Desktop/example/node_modules/graphql-middleware/dist/validation.js:15:43
    at Array.forEach (<anonymous>)
    at Object.validateMiddleware (/Users/user/Desktop/example/node_modules/graphql-middleware/dist/validation.js:9:29)
    at addMiddlewareToSchema (/Users/user/Desktop/example/node_modules/graphql-middleware/dist/middleware.js:19:42)
    at normalisedMiddlewares.reduceRight.schema.schema (/Users/user/Desktop/example/node_modules/graphql-middleware/dist/middleware.js:52:87)
    at Array.reduceRight (<anonymous>)
    at applyMiddlewareWithOptions (/Users/user/Desktop/example/node_modules/graphql-middleware/dist/middleware.js:51:79)
    at applyMiddleware (/Users/user/Desktop/example/node_modules/graphql-middleware/dist/middleware.js:78:12)
```

----
```diff
const {
    GraphQLServer
} = require('graphql-yoga')

const typeDefs = `
  type Query {
    open: String!
    secured: String!
    me: Me!
  }

  type Me {
    name: String!
    surname: String!
    age: Int!
  }
`

const code = 'supersecret'
const isLoggedIn = async (resolve, parent, args, ctx, info) => {
    // Include your agent code as Authorization: <token> header.
    const permit = ctx.request.get('Authorization') === code

    if (!permit) {
        throw new Error(`Not authorised!`)
    }

    return resolve()
}

+ const log = async (resolve, parent, args, ctx, info) => {
+     console.log('Aqwertyuiop');
+     return resolve()
+ }

const resolvers = {
    Query: {
        open: () => `Open data, everyone's welcome!`,
        secured: () => `Personal diary - this is for my eyes only!`,
        me: () => ({}),
    },
    Me: {
        name: () => 'Ben',
        surname: () => 'Cool',
        age: () => 18,
    },
}

// Middleware - Permissions

const permissions = {
    Query: {
+        secured: [log, isLoggedIn],
-        secured: isLoggedIn,
    },
    Me: isLoggedIn,
}

// Server

const server = new GraphQLServer({
    typeDefs,
    resolvers,
    context: req => ({
        ...req
    }),
    middlewares: [permissions],
})

server.start(() => console.log('Server is running on http://localhost:4000'))

```

Is there any support for multiple middle-wares?
There can be an utility function or in-build support for multiple middleware.

**Comment by Faisal-Manzer** [comment]
This can be easily solved by an utility function
```js
const combineMiddlewares = (...middlewares) => async (resolve, parent, args, ctx, info) => {
    if (middlewares.length === 0) return resolve();
    const middleware = middlewares.pop();
    const next = () => combineMiddlewares(...middlewares)(resolve, parent, args, ctx, info);
    return await middleware(next, parent, args, ctx, info);
}
```

So, now it works
```js
const permissions = {
    Query: {
        secured: combineMiddlewares (log, isLoggedIn),
        secured: isLoggedIn,
    },
    Me: isLoggedIn,
}
```

Can we have some builtin support rather than using workarounds?

**Comment by maticzav** [comment]
There's a built in support. You may add multiple middlewares and graphql middleware should handle them. That's why there's a list parameter for `middlewares` not a singleton.

**Comment by Faisal-Manzer** [comment]
Can you give some code example?

**Comment by maticzav** [comment]
https://github.com/prisma-labs/graphql-middleware/blob/master/README.md#how-does-it-work
